# Core configuration for reproduction
paths:
  proposals_csv: data/Annotation_and_Mapping_Combined.csv
  gold_csv: data/consensus_49.csv
  out_dir: artifacts

thresholds:
  k_raw_consensus: 5     # models
  k_intra: 6             # runs
  k_inter: 2             # models (post-CoT)

# Column mapping (best-effort matching to handle slight schema variations)
columns:
  class: ["class", "Class", "class_name"]
  method: ["method", "Method", "method_name"]
  model: ["model", "Model", "llm", "LLM"]
  run: ["run", "Run", "sample", "Sample"]
